name: unit_tree_data_structure
description: "The tree data structure that supports recursive_tree_flutter packages"
version: 1.0.0
repository: https://github.com/nvbien2000/unit_tree_data_structure

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
